### ISSUE TITLE
Some error during training

### ISSUE THREAD

**Issue by yfzhang114** [JeanKaddour/SIN#1]
![image](https://user-images.githubusercontent.com/53161950/143724792-ac79b667-a6d2-4dd8-b07a-5349db154fb1.png)

![image](https://user-images.githubusercontent.com/53161950/143724804-cb3f8287-3ca6-419a-804b-1b0daf41421a.png)

why return none here?

**Comment by JeanKaddour** [comment]
Thank you for question and interest in our work.

This error is raised within pytorch's `DataLoader` class (here, by the `train_loader` instance). So my guess would be that the way you're currently creating the dataset/dataloader does not work properly. Can you post a minimal working example to reproduce this error?

**Comment by yfzhang114** [comment]
Very interesting work! thanks for your response. I fixed the error by manipulating the input shape and revising the __cat_dim__ function.

![image](https://user-images.githubusercontent.com/53161950/143765546-6b17f227-c8e4-494a-957f-0ddb383c94af.png)

![image](https://user-images.githubusercontent.com/53161950/143765551-c15b422e-8dbb-4eb5-a174-75ce7756ee70.png)

**Comment by JeanKaddour** [comment]
Thank you very much!

**Comment by JeanKaddour** [comment]
I think that these issues arise when using PyG 2 instead of PyG 1.x. 
I will try to fix this soon. Thank you for making me aware of this!
