### ISSUE TITLE
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 9301  error when running code 

### ISSUE THREAD

**Issue by HarshaSatyavardhan** [JeanKaddour/SIN#3]
I am facing this error when trying to run the codes, why is this happening?
`RuntimeError: split_with_sizes expects split_sizes to sum exactly to 9301 (input tensor's size at dimension 0), but got split_sizes=[0, 7566, 638]`

![Screenshot 2023-01-28 at 9 06 47 PM](https://user-images.githubusercontent.com/41695878/215275460-4c0219f4-74ba-4331-9398-aad5ff9ed737.png)
![Screenshot 2023-01-28 at 9 07 10 PM](https://user-images.githubusercontent.com/41695878/215275450-5c5b018b-8b8d-4215-8bc8-f70cbfb31a27.png)

**Comment by JeanKaddour** [comment]
I'm not sure; I haven't encountered this issue before. Looks like a torch/torch-geometric issue. Which versions are you using?

Also, am I understanding correctly from the screenshots that this happens late during training, i.e., at Epoch 388? If so, it's likely a training instability. Is this an experiment reproduction from the paper, or are you running it with different hparams/data/etc.?

**Comment by HarshaSatyavardhan** [comment]
I am using torch-geometric==2.2.0 and torch==1.13.1 versions.

Yes, Its the reproduction of the paper. I just git cloned the repo in Colab and started training.

**Comment by JeanKaddour** [comment]
Could you please try with 

```
torch==1.10.2
torch-cluster==1.5.9
torch-geometric==2.0.3
torch-scatter==2.0.9
torch-sparse==0.6.12
torch-spline-conv==1.2.1
```

With these versions, I recently reproduced the results
